config/routes.rb
Rails.application.routes.draw do
  resources:candidates
end





# REST
# GET /members => list all 列出所有會員資料
# GET /members/2 觀看二號會員資料
# GET /members/2/edit 編輯2號會員資料 


# REST
# GET /books => list all 列出所有書的資料
# GET /books/2 觀看二號會員資料
# GET /books/2/edit 編輯第二本書的資料 

# rails routes 印出專案內所有路徑對照表

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord

    validates :name, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController


    def index
        @candidates =Candidate.all
    end

    def new
        @candidate = Candidate.new
    end
    def show

        
    end

    def create

        @candidate = Candidate.new(candidate_params)

        if@candidate.save
            flash[:notice] = "Candidate rewxw"
            redirect_to '/candidates'
        else
            render:new
        end
    end


    private
    def candidate_params
        params.require(:candidate).permit(:name, :party,:age,:politics)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/index.html.erb
<%= flash[:notice] %>

<h1>hello</h1>


<%= link_to 'Add Candidate', new_candidate_path %>


<table>
    <tr>
        <td>Name</td>
        <td>Party</td>
        <td>Age</td>
        <td>Politics</td>
        <td>Action</td>
    </tr>

    <% @candidates.each do |candidate| %>
    <tr>
        <td><%= link_to candidate.name, candidate_path(candidate.id) %></a></td>
        <td><%= candidate.party %></td>
        <td><%= candidate.age %></td>
        <td><%= candidate.politics %></td>
        <td>Action</td>
    </tr>
    <% end %>
</table>

app/views/candidates/new.html.erb
<h1>add Candidate</h1>


<%= form_for(@candidate) do |form| %>

<div>
    <%= form.label:name %>
    <%= form.text_field :name %>
</div>
<div>
    <%= form.label:party %>
    <%= form.text_field :party %>
    
</div>
<div>
    <%= form.label:age %>
    <%= form.text_field :age %>
</div>
<div>
    <%= form.label:politics %>
    <%= form.text_area :politics %>
</div>

    <%= form.submit%>
    <% end %>

app/views/candidates/show.html.erb
<h1>...</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>